name: Continuous Integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install and Lint
        run: |
          if [ -f package.json ]; then npm install && npm run lint --if-present; fi
